// BOLT 11 conformance tests, driven by the spec's own test vectors.
//
//   npm test
//
// Vectors live in test/vectors.js and are generated by test/extract-vectors.js.

const { test, describe } = require('node:test');
const assert = require('node:assert');

const { load } = require('./load.js');
const { VALID_VECTORS, INVALID_VECTORS } = require('./vectors.js');

const lndecode = load();

describe('valid vectors decode', () => {
    for (const { description, invoice } of VALID_VECTORS) {
        test(description, () => {
            const decoded = lndecode.decode(invoice);
            assert.ok(decoded.human_readable_part.prefix, 'prefix should be set');
            assert.ok(Number.isInteger(decoded.data.time_stamp), 'timestamp should be an integer');
            assert.match(decoded.checksum, /^[0-9a-z]{6}$/, 'checksum should be 6 bech32 chars');
        });
    }
});

describe('invalid vectors are rejected', () => {
    for (const { description, invoice } of INVALID_VECTORS) {
        test(description, () => {
            assert.throws(() => lndecode.decode(invoice));
        });
    }
});

describe('human-readable part', () => {
    test('all-uppercase is accepted', () => {
        const upper = VALID_VECTORS.find(v => /all upper case/i.test(v.description));
        assert.ok(upper, 'spec should contain an all-uppercase vector');
        assert.doesNotThrow(() => lndecode.decode(upper.invoice));
    });

    test('mixed case is rejected', () => {
        const mixed = INVALID_VECTORS.find(v => /mixed case/i.test(v.description));
        assert.ok(mixed, 'spec should contain a mixed-case vector');
        assert.throws(() => lndecode.decode(mixed.invoice), /mixed case/i);
    });

    // Exercised directly: a synthetic full invoice would fail the checksum first.
    test('unknown prefix is rejected', () => {
        assert.throws(() => lndecode.decodeHumanReadablePart('lnxx2500u'), /prefix/i);
    });

    test('known prefixes are accepted', () => {
        for (const prefix of ['lnbc', 'lntb', 'lnbcrt', 'lntbs']) {
            assert.doesNotThrow(() => lndecode.decodeHumanReadablePart(prefix + '25m'), prefix);
        }
    });
});

describe('amount multipliers', () => {
    const cases = [
        ['', 'Any amount'],
        ['25m', 2500000000],
        ['1500n', 150000],
        ['2500u', 250000000],
        ['2500000000p', 250000000],
        ['10p', 1]
    ];
    for (const [input, expected] of cases) {
        test(`"${input || '(empty)'}" -> ${expected}`, () => {
            assert.strictEqual(lndecode.decodeAmount(input), expected);
        });
    }

    // Spec: if the multiplier is 'p', the last decimal of amount MUST be 0,
    // because HTLCs are denominated in millisatoshis.
    for (const input of ['1p', '2500000001p', '999p']) {
        test(`"${input}" is rejected as sub-millisatoshi`, () => {
            assert.throws(() => lndecode.decodeAmount(input), /sub-millisatoshi/i);
        });
    }

    test('leading zeros are rejected', () => {
        assert.throws(() => lndecode.decodeAmount('025m'), /leading zeros/i);
    });

    test('undefined multiplier is rejected', () => {
        assert.throws(() => lndecode.decodeAmount('2500x'), /multiplier/i);
    });
});

describe('payment secret', () => {
    test('an invoice without a valid s field is rejected', () => {
        const missing = INVALID_VECTORS.find(v => /Missing required .?s.? field/i.test(v.description));
        assert.ok(missing, 'spec should contain a missing-s vector');
        assert.throws(() => lndecode.decode(missing.invoice), /payment secret/i);
    });

    test('every valid vector exposes a payment secret', () => {
        for (const { description, invoice } of VALID_VECTORS) {
            const tags = lndecode.decode(invoice).data.tags;
            assert.ok(tags.some(t => t.type === 's'), `${description} should carry an s field`);
        }
    });
});

describe('structural validation', () => {
    test('a truncated data part is rejected on length', () => {
        const short = INVALID_VECTORS.find(v => /too short/i.test(v.description));
        assert.ok(short, 'spec should contain a too-short vector');
        assert.throws(() => lndecode.decode(short.invoice), /too short/i);
    });

    test('a data part one character short is rejected', () => {
        // 7 timestamp + 104 signature is the minimum
        assert.throws(() => lndecode.decode('lnbc1' + 'q'.repeat(110) + 'qqqqqq'), /too short/i);
    });

    test('a missing separator is reported as such', () => {
        assert.throws(() => lndecode.decode('lnbcqqqqqq'), /missing separator/i);
    });
});

describe('routing information', () => {
    test('every hop of a multi-hop r field is decoded', () => {
        const vector = VALID_VECTORS.find(v => /extra routing info/i.test(v.description));
        assert.ok(vector, 'spec should contain a multi-hop routing vector');
        const routing = lndecode.decode(vector.invoice).data.tags.find(tag => tag.type === 'r');
        assert.strictEqual(routing.value.length, 2);
        assert.notStrictEqual(routing.value[0].public_key, routing.value[1].public_key);
        assert.strictEqual(routing.value[0].fee_base_msat, 1);
        assert.strictEqual(routing.value[1].fee_base_msat, 2);
        assert.strictEqual(routing.value[1].fee_proportional_millionths, 30);
        assert.strictEqual(routing.value[1].cltv_expiry_delta, 4);
    });

    test('a 32-bit field above 2^31 is read unsigned', () => {
        assert.strictEqual(lndecode.byteArrayToInt([0x80, 0, 0, 0]), 2147483648);
        assert.strictEqual(lndecode.byteArrayToInt([0xff, 0xff, 0xff, 0xff]), 4294967295);
    });
});

describe('payment metadata', () => {
    test('an m field is decoded rather than skipped', () => {
        const vector = VALID_VECTORS.find(v => /payment metadata/i.test(v.description));
        assert.ok(vector, 'spec should contain a metadata vector');
        const metadata = lndecode.decode(vector.invoice).data.tags.find(tag => tag.type === 'm');
        assert.ok(metadata, 'the m field should be decoded');
        assert.strictEqual(metadata.value, '01fafaf0');
    });
});

describe('min_final_cltv_expiry_delta', () => {
    test('the c field carries the current name', () => {
        const vector = VALID_VECTORS.find(v => /list of items/i.test(v.description));
        const c = lndecode.decode(vector.invoice).data.tags.find(tag => tag.type === 'c');
        assert.ok(c, 'that vector should carry a c field');
        assert.strictEqual(c.description, 'min_final_cltv_expiry_delta');
    });
});

describe('feature bits', () => {
    test('unknown even bit is rejected', () => {
        const bad = INVALID_VECTORS.find(v => /unknown feature 100/i.test(v.description));
        assert.ok(bad, 'spec should contain an unknown-even-feature vector');
        assert.throws(() => lndecode.decode(bad.invoice), /feature bit/i);
    });

    // The spec pairs bit 100 (even, must fail) against bit 99 (odd, must be
    // ignored); several valid vectors set 99.
    test('unknown odd bit is ignored', () => {
        const withOddBit = VALID_VECTORS.filter(v => {
            const features = lndecode.decode(v.invoice).data.tags.find(t => t.type === '9');
            if (!features) return false;
            const bits = features.value;
            return bits.length > 99 && bits.charAt(bits.length - 1 - 99) === '1';
        });
        assert.ok(withOddBit.length > 0, 'spec should have vectors setting odd bit 99');
    });
});
