// BOLT 11 conformance tests, driven by the spec's own test vectors.
//
//   npm test
//
// Vectors live in test/vectors.js and are generated by test/extract-vectors.js.

const { test, describe } = require('node:test');
const assert = require('node:assert');

const { load } = require('./load.js');
const { VALID_VECTORS, INVALID_VECTORS } = require('./vectors.js');

const lndecode = load();

// Invalid vectors whose rule is not implemented yet. These run and are reported
// as TODO rather than failing the suite, so the remaining gaps stay visible.
// Remove an entry as soon as the corresponding rule lands.
const NOT_YET_ENFORCED = new Map([
    ['Signature is not recoverable.',
        'signature validation needs secp256k1'],
    ["Non canonical signature (high-S) with 'n' field defined",
        'low-S enforcement needs secp256k1']
]);

describe('valid vectors decode', () => {
    for (const { description, invoice } of VALID_VECTORS) {
        test(description, () => {
            const decoded = lndecode.decode(invoice);
            assert.ok(decoded.human_readable_part.prefix, 'prefix should be set');
            assert.ok(Number.isInteger(decoded.data.time_stamp), 'timestamp should be an integer');
            assert.match(decoded.checksum, /^[0-9a-z]{6}$/, 'checksum should be 6 bech32 chars');
        });
    }
});

describe('invalid vectors are rejected', () => {
    for (const { description, invoice } of INVALID_VECTORS) {
        const pending = NOT_YET_ENFORCED.get(description);
        const options = pending ? { todo: pending } : {};
        test(description, options, () => {
            assert.throws(() => lndecode.decode(invoice));
        });
    }
});

describe('human-readable part', () => {
    test('all-uppercase is accepted', () => {
        const upper = VALID_VECTORS.find(v => /all upper case/i.test(v.description));
        assert.ok(upper, 'spec should contain an all-uppercase vector');
        assert.doesNotThrow(() => lndecode.decode(upper.invoice));
    });

    test('mixed case is rejected', () => {
        const mixed = INVALID_VECTORS.find(v => /mixed case/i.test(v.description));
        assert.ok(mixed, 'spec should contain a mixed-case vector');
        assert.throws(() => lndecode.decode(mixed.invoice), /mixed case/i);
    });

    // Exercised directly: a synthetic full invoice would fail the checksum first.
    test('unknown prefix is rejected', () => {
        assert.throws(() => lndecode.decodeHumanReadablePart('lnxx2500u'), /prefix/i);
    });

    test('known prefixes are accepted', () => {
        for (const prefix of ['lnbc', 'lntb', 'lnbcrt', 'lntbs']) {
            assert.doesNotThrow(() => lndecode.decodeHumanReadablePart(prefix + '25m'), prefix);
        }
    });
});

describe('amount multipliers', () => {
    const cases = [
        ['', 'Any amount'],
        ['25m', 2500000000],
        ['1500n', 150000],
        ['2500u', 250000000],
        ['2500000000p', 250000000],
        ['10p', 1]
    ];
    for (const [input, expected] of cases) {
        test(`"${input || '(empty)'}" -> ${expected}`, () => {
            assert.strictEqual(lndecode.decodeAmount(input), expected);
        });
    }

    // Spec: if the multiplier is 'p', the last decimal of amount MUST be 0,
    // because HTLCs are denominated in millisatoshis.
    for (const input of ['1p', '2500000001p', '999p']) {
        test(`"${input}" is rejected as sub-millisatoshi`, () => {
            assert.throws(() => lndecode.decodeAmount(input), /sub-millisatoshi/i);
        });
    }

    test('leading zeros are rejected', () => {
        assert.throws(() => lndecode.decodeAmount('025m'), /leading zeros/i);
    });

    test('undefined multiplier is rejected', () => {
        assert.throws(() => lndecode.decodeAmount('2500x'), /multiplier/i);
    });
});

describe('payment secret', () => {
    test('an invoice without a valid s field is rejected', () => {
        const missing = INVALID_VECTORS.find(v => /Missing required .?s.? field/i.test(v.description));
        assert.ok(missing, 'spec should contain a missing-s vector');
        assert.throws(() => lndecode.decode(missing.invoice), /payment secret/i);
    });

    test('every valid vector exposes a payment secret', () => {
        for (const { description, invoice } of VALID_VECTORS) {
            const tags = lndecode.decode(invoice).data.tags;
            assert.ok(tags.some(t => t.type === 's'), `${description} should carry an s field`);
        }
    });
});

describe('structural validation', () => {
    // The "too short" vector is currently rejected only because it carries no valid
    // 's' field. There is still no length check, so a truncated invoice that happens
    // to contain an 's' field would decode into garbage: negative substring indices
    // clamp to 0 and produce a fabricated signature.
    test('a truncated data part is rejected on length', {
        todo: 'minimum-length validation not implemented'
    }, () => {
        const short = INVALID_VECTORS.find(v => /too short/i.test(v.description));
        assert.ok(short, 'spec should contain a too-short vector');
        assert.throws(() => lndecode.decode(short.invoice), /short|length/i);
    });
});

describe('feature bits', () => {
    test('unknown even bit is rejected', () => {
        const bad = INVALID_VECTORS.find(v => /unknown feature 100/i.test(v.description));
        assert.ok(bad, 'spec should contain an unknown-even-feature vector');
        assert.throws(() => lndecode.decode(bad.invoice), /feature bit/i);
    });

    // The spec pairs bit 100 (even, must fail) against bit 99 (odd, must be
    // ignored); several valid vectors set 99.
    test('unknown odd bit is ignored', () => {
        const withOddBit = VALID_VECTORS.filter(v => {
            const features = lndecode.decode(v.invoice).data.tags.find(t => t.type === '9');
            if (!features) return false;
            const bits = features.value;
            return bits.length > 99 && bits.charAt(bits.length - 1 - 99) === '1';
        });
        assert.ok(withOddBit.length > 0, 'spec should have vectors setting odd bit 99');
    });
});
